### ISSUE TITLE
Error when using the test plugin on Intelij on linux ubuntu

### ISSUE THREAD

**Issue by Maharal** [artspb/idea-pitest#4]
`/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -javaagent:/home/raphael/Downloads/idea-IC-203.7717.56/lib/idea_rt.jar=37993:/home/raphael/Downloads/idea-IC-203.7717.56/bin -Dfile.encoding=UTF-8 -classpath /home/raphael/.local/share/JetBrains/IdeaIC2020.3/pit-idea-plugin/lib/pitest-junit5-plugin-0.12.jar:/home/raphael/.local/share/JetBrains/IdeaIC2020.3/pit-idea-plugin/lib/xpp3_min-1.1.4c.jar:/home/raphael/.local/share/JetBrains/IdeaIC2020.3/pit-idea-plugin/lib/xmlpull-1.1.3.1.jar:/home/raphael/.local/share/JetBrains/IdeaIC2020.3/pit-idea-plugin/lib/xstream-1.4.8.jar:/home/raphael/.local/share/JetBrains/IdeaIC2020.3/pit-idea-plugin/lib/pitest-entry-1.6.3.jar:/home/raphael/.local/share/JetBrains/IdeaIC2020.3/pit-idea-plugin/lib/pitest-command-line-1.6.3.jar:/home/raphael/.local/share/JetBrains/IdeaIC2020.3/pit-idea-plugin/lib/pitest-1.6.3.jar:/home/raphael/IdeaProjects/untitled/out/production/untitled:/home/raphael/.m2/repository/org/junit/jupiter/junit-jupiter/5.4.2/junit-jupiter-5.4.2.jar:/home/raphael/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.4.2/junit-jupiter-api-5.4.2.jar:/home/raphael/.m2/repository/org/apiguardian/apiguardian-api/1.0.0/apiguardian-api-1.0.0.jar:/home/raphael/.m2/repository/org/opentest4j/opentest4j/1.1.1/opentest4j-1.1.1.jar:/home/raphael/.m2/repository/org/junit/platform/junit-platform-commons/1.4.2/junit-platform-commons-1.4.2.jar:/home/raphael/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.4.2/junit-jupiter-params-5.4.2.jar:/home/raphael/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.4.2/junit-jupiter-engine-5.4.2.jar:/home/raphael/.m2/repository/org/junit/platform/junit-platform-engine/1.4.2/junit-platform-engine-1.4.2.jar org.pitest.mutationtest.commandline.MutationCoverageReport --reportDir /home/raphael/IdeaProjects/untitled/report --sourceDirs /home/raphael/IdeaProjects/untitled/src --targetClasses com.* --outputFormats XML,HTML
22:04:36 PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
22:04:36 PIT >> INFO : Sending 3 test classes to minion
22:04:36 PIT >> INFO : Sent tests to minion
22:04:36 PIT >> SEVERE : Error generating coverage. Please check that your classpath contains modern JUnit 4 or PIT test plugin for other test tool (JUnit 5, TestNG, ...) is enabled.
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally. Please check the classpath and/or enable test plugin for used test tool.

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Ubuntu
Version : 11.0.10+9-Ubuntu-0ubuntu1.20.04
Uptime : 1388
Input -> 
 1 : -javaagent:/home/raphael/Downloads/idea-IC-203.7717.56/lib/idea_rt.jar=37993:/home/raphael/Downloads/idea-IC-203.7717.56/bin
 2 : -Dfile.encoding=UTF-8
BootClassPathSupported : false

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Ubuntu
Version : 11.0.10+9-Ubuntu-0ubuntu1.20.04
Uptime : 1389
Input -> 
 1 : -javaagent:/home/raphael/Downloads/idea-IC-203.7717.56/lib/idea_rt.jar=37993:/home/raphael/Downloads/idea-IC-203.7717.56/bin
 2 : -Dfile.encoding=UTF-8
BootClassPathSupported : false

	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:105)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:51)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:121)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:50)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally. Please check the classpath and/or enable test plugin for used test tool.

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Ubuntu
Version : 11.0.10+9-Ubuntu-0ubuntu1.20.04
Uptime : 1388
Input -> 
 1 : -javaagent:/home/raphael/Downloads/idea-IC-203.7717.56/lib/idea_rt.jar=37993:/home/raphael/Downloads/idea-IC-203.7717.56/bin
 2 : -Dfile.encoding=UTF-8
BootClassPathSupported : false

	at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:143)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:89)
	... 6 more

Process finished with exit code 1
Open report in browser`

**Comment by artspb** [comment]
Sorry, the plugin isn't updated for quite a while and not supported. You're on your own.
